ALTER TABLE "Client"
DROP CONSTRAINT "FK_UserId",
ADD CONSTRAINT "FK_UserId" FOREIGN KEY ("UserId") REFERENCES "User"("Id") ON DELETE CASCADE;

ALTER TABLE "Sender"
DROP CONSTRAINT "FK_UserId",
ADD CONSTRAINT "FK_UserId" FOREIGN KEY ("UserId") REFERENCES "User"("Id") ON DELETE CASCADE;

ALTER TABLE "Courier"
DROP CONSTRAINT "FK_UserId",
ADD CONSTRAINT "FK_UserId" FOREIGN KEY ("UserId") REFERENCES "User"("Id") ON DELETE CASCADE;

alter table "User"
add column "IsApproved" boolean;